#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
export DJANGO_SETTINGS_MODULE=signscloud.settings
python manage.py makemigrations supermarket
python manage.py migrate
python manage.py runserver 0.0.0.0:8000