# Generated by Django 4.0.7 on 2023-03-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stores',
            field=models.ManyToManyField(to='supermarket.stores'),
        ),
    ]
