# Generated by Django 4.0.7 on 2023-03-07 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0002_user_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stores',
        ),
        migrations.AddField(
            model_name='stores',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
